CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    staff_id VARCHAR(255) NOT NULL UNIQUE,
    profile_photo_data BLOB,
    profile_photo_type VARCHAR(255),
    cover_photo_data BLOB,
    cover_photo_type VARCHAR(255)
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo_data BLOB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_photo_type VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS cover_photo_data BLOB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cover_photo_type VARCHAR(255);

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_by_id BIGINT NOT NULL,
    CONSTRAINT fk_rooms_created_by FOREIGN KEY (created_by_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS room_members (
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (room_id, user_id),
    CONSTRAINT fk_room_members_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_room_members_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000) NOT NULL,
    sent_to VARCHAR(255) NOT NULL,
    sender_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT fk_messages_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(255) NOT NULL,
    assigned_by_id BIGINT NOT NULL,
    assigned_to_id BIGINT NOT NULL,
    CONSTRAINT fk_tasks_assigned_by FOREIGN KEY (assigned_by_id) REFERENCES users(id),
    CONSTRAINT fk_tasks_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    type VARCHAR(255) NOT NULL,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    recipient_id BIGINT NOT NULL,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS voice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    room_id BIGINT NOT NULL,
    started_by_id BIGINT NOT NULL,
    CONSTRAINT fk_voice_sessions_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_voice_sessions_started_by FOREIGN KEY (started_by_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS file_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_data BLOB,
    uploaded_by_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    CONSTRAINT fk_file_resources_uploaded_by FOREIGN KEY (uploaded_by_id) REFERENCES users(id),
    CONSTRAINT fk_file_resources_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

ALTER TABLE file_resources ADD COLUMN IF NOT EXISTS file_data BLOB;

CREATE TABLE IF NOT EXISTS login_otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL
);
