-- Final Production Schema for PostgreSQL
-- This script consolidates all required columns and fixes OID/BYTEA issues.

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(32) NOT NULL,
    active BOOLEAN NOT NULL,
    staff_id VARCHAR(32) NOT NULL UNIQUE,
    bio VARCHAR(3000),
    skills_csv VARCHAR(2000),
    exp1_role VARCHAR(255),
    exp1_years VARCHAR(255),
    exp2_role VARCHAR(255),
    exp2_years VARCHAR(255),
    exp3_role VARCHAR(255),
    exp3_years VARCHAR(255),
    github_link VARCHAR(255),
    twitter_link VARCHAR(255),
    linkedin_link VARCHAR(255),
    chat_backgrounds_json TEXT,
    ai_chat_history_json TEXT,
    profile_photo_data BYTEA,
    profile_photo_type VARCHAR(255),
    cover_photo_data BYTEA,
    cover_photo_type VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL,
    created_by_id BIGINT NOT NULL,
    CONSTRAINT fk_rooms_created_by FOREIGN KEY (created_by_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS room_members (
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (room_id, user_id),
    CONSTRAINT fk_room_members_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_room_members_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(2000) NOT NULL,
    sent_to VARCHAR(255) NOT NULL,
    sender_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users(id),
    CONSTRAINT fk_messages_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(255) NOT NULL,
    deadline TIMESTAMP,
    seen_by_staff BOOLEAN DEFAULT FALSE NOT NULL,
    assigned_by_id BIGINT NOT NULL,
    assigned_to_id BIGINT NOT NULL,
    CONSTRAINT fk_tasks_assigned_by FOREIGN KEY (assigned_by_id) REFERENCES users(id),
    CONSTRAINT fk_tasks_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    type VARCHAR(255) NOT NULL,
    task_id BIGINT,
    read BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    recipient_id BIGINT NOT NULL,
    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS voice_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN NOT NULL,
    room_id BIGINT NOT NULL,
    started_by_id BIGINT NOT NULL,
    CONSTRAINT fk_voice_sessions_room FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_voice_sessions_started_by FOREIGN KEY (started_by_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS file_resources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    file_data BYTEA NOT NULL,
    uploaded_by_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,
    CONSTRAINT fk_file_resources_uploaded_by FOREIGN KEY (uploaded_by_id) REFERENCES users(id),
    CONSTRAINT fk_file_resources_room FOREIGN KEY (room_id) REFERENCES rooms(id)
);

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    caption VARCHAR(5000),
    created_at TIMESTAMP NOT NULL,
    media_name VARCHAR(255),
    media_type VARCHAR(255),
    media_data BYTEA,
    author_id BIGINT NOT NULL,
    CONSTRAINT fk_posts_author FOREIGN KEY (author_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS post_comments (
    post_id BIGINT NOT NULL,
    comment_order INTEGER NOT NULL,
    user_id BIGINT NOT NULL,
    author_id BIGINT NOT NULL,
    user_name VARCHAR(255) NOT NULL,
    text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (post_id, comment_order),
    CONSTRAINT fk_post_comments_post FOREIGN KEY (post_id) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS post_likes (
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_post_likes_post FOREIGN KEY (post_id) REFERENCES posts(id)
);

CREATE TABLE IF NOT EXISTS login_otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP NOT NULL
);
